COLOR_CODES = {
    "ALICEBLUE": "#F0F8FF",
    "ANTIQUEWHITE": "#FAEBD7",
    "AQUA": "#00FFFF",
    "BISQUE": "#FFE4C4",
    "CORNFLOWERBLUE": "#6495ED",
    "DARKORANGE": "#FF8C00",
    "GOLD": "#FFD700",
    "LAVENDER": "#E6E6FA",
    "MEDIUMSPRINGGREEN": "#00FA9A",
    "TOMATO": "#FF6347"
}
